// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function FetchEmails() {
  return window['go']['main']['App']['FetchEmails']();
}

export function FetchInterviews() {
  return window['go']['main']['App']['FetchInterviews']();
}

export function GerarDossieEstudos(arg1) {
  return window['go']['main']['App']['GerarDossieEstudos'](arg1);
}

export function LoadSettings() {
  return window['go']['main']['App']['LoadSettings']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function StartDaemon(arg1) {
  return window['go']['main']['App']['StartDaemon'](arg1);
}

export function SyncEmailsRoutine() {
  return window['go']['main']['App']['SyncEmailsRoutine']();
}

export function UploadAndParseCV() {
  return window['go']['main']['App']['UploadAndParseCV']();
}

export function VerifyIMAP(arg1) {
  return window['go']['main']['App']['VerifyIMAP'](arg1);
}
