// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearPersistedSecret(arg1) {
  return window['go']['main']['App']['ClearPersistedSecret'](arg1);
}

export function ClearPersistedSecrets() {
  return window['go']['main']['App']['ClearPersistedSecrets']();
}

export function ConnectLinkedInSession() {
  return window['go']['main']['App']['ConnectLinkedInSession']();
}

export function FetchEmails() {
  return window['go']['main']['App']['FetchEmails']();
}

export function FetchHistory() {
  return window['go']['main']['App']['FetchHistory']();
}

export function FetchInterviews() {
  return window['go']['main']['App']['FetchInterviews']();
}

export function FetchProspectedJobs() {
  return window['go']['main']['App']['FetchProspectedJobs']();
}

export function GenerateOutreachMessage(arg1, arg2) {
  return window['go']['main']['App']['GenerateOutreachMessage'](arg1, arg2);
}

export function GerarDossieEstudos(arg1) {
  return window['go']['main']['App']['GerarDossieEstudos'](arg1);
}

export function GetAutomationPipelineStatus() {
  return window['go']['main']['App']['GetAutomationPipelineStatus']();
}

export function GetProspectedMetrics() {
  return window['go']['main']['App']['GetProspectedMetrics']();
}

export function GetSystemStatus() {
  return window['go']['main']['App']['GetSystemStatus']();
}

export function LoadSettings() {
  return window['go']['main']['App']['LoadSettings']();
}

export function RunPerformanceSuite() {
  return window['go']['main']['App']['RunPerformanceSuite']();
}

export function SaveSettings(arg1) {
  return window['go']['main']['App']['SaveSettings'](arg1);
}

export function StartAutomationPipeline(arg1) {
  return window['go']['main']['App']['StartAutomationPipeline'](arg1);
}

export function StartDaemon(arg1) {
  return window['go']['main']['App']['StartDaemon'](arg1);
}

export function SyncEmailsRoutine() {
  return window['go']['main']['App']['SyncEmailsRoutine']();
}

export function UploadAndParseCV() {
  return window['go']['main']['App']['UploadAndParseCV']();
}

export function VerifyIMAP(arg1) {
  return window['go']['main']['App']['VerifyIMAP'](arg1);
}

export function VerifySingleCredential(arg1, arg2) {
  return window['go']['main']['App']['VerifySingleCredential'](arg1, arg2);
}
