// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function FetchEmails():Promise<Array<main.EmailRecrutador>>;

export function FetchInterviews():Promise<Array<main.EmailRecrutador>>;

export function GerarDossieEstudos(arg1:string):Promise<string>;

export function LoadSettings():Promise<main.SettingsDTO>;

export function SaveSettings(arg1:main.SettingsDTO):Promise<boolean>;

export function StartDaemon(arg1:main.ProfileDTO):Promise<boolean>;

export function SyncEmailsRoutine():Promise<void>;

export function UploadAndParseCV():Promise<main.ProfileDTO>;

export function VerifyIMAP(arg1:main.SettingsDTO):Promise<boolean>;
