// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function FetchEmails():Promise<Array<main.EmailRecrutador>>;

export function FetchHistory():Promise<Array<main.VagaHistoricoDTO>>;

export function FetchInterviews():Promise<Array<main.EmailRecrutador>>;

export function FetchProspectedJobs():Promise<Array<main.ProspectedJobDTO>>;

export function GenerateOutreachMessage(arg1:string,arg2:string):Promise<string>;

export function GerarDossieEstudos(arg1:string):Promise<string>;

export function GetProspectedMetrics():Promise<main.ProspectedMetricsDTO>;

export function GetSystemStatus():Promise<Record<string, any>>;

export function LoadSettings():Promise<main.SettingsDTO>;

export function RunPerformanceSuite():Promise<main.PerformanceSuiteDTO>;

export function SaveSettings(arg1:main.SettingsDTO):Promise<boolean>;

export function StartDaemon(arg1:main.ProfileDTO):Promise<boolean>;

export function SyncEmailsRoutine():Promise<void>;

export function UploadAndParseCV():Promise<main.ProfileDTO>;

export function VerifyIMAP(arg1:main.SettingsDTO):Promise<boolean>;
