// Package domain contains pure business entities for GhostApply.
// Zero external dependencies — this is the innermost Clean Arch ring.
package domain

// Status represents the lifecycle state of a Vaga or Candidatura.
// Using a typed string (newtype pattern) prevents passing arbitrary strings.
type Status string

const (
	// StatusNova is assigned when the vaga is first scraped.
	StatusNova Status = "NOVA"

	// StatusPendente means the vaga is queued for AI analysis.
	StatusPendente Status = "PENDENTE"

	// StatusAnalisada means the vaga was analyzed by the Rust worker.
	StatusAnalisada Status = "ANALISADA"

	// StatusForjado means the job has a generated PDF resume.
	StatusForjado Status = "FORJADO"

	// StatusAplicada means the filler successfully applied to the job.
	StatusAplicada Status = "APLICADA"

	// StatusErro means the filler or worker encountered an unrecoverable error.
	StatusErro Status = "ERRO"

	// StatusRejeitadoPresencial means Groq rejected it as non-remote.
	StatusRejeitadoPresencial Status = "REJEITADO_PRESENCIAL"

	// StatusDescartada means the vaga was filtered out.
	StatusDescartada Status = "DESCARTADA"
)

// Vaga represents a job posting captured from a job portal.
//
// ID must be a UUID v4 generated by the caller.
// URL is the idempotency key — duplicate scrapes are silently ignored via INSERT OR IGNORE.
type Vaga struct {
	ID       string
	Titulo   string
	Empresa  string
	URL      string
	Descricao string
	Status   Status
}
